//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.WPF.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TabControlLeftResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabControlLeftResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GM.WPF.Controls.TabControlLeftResource", typeof(TabControlLeftResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ControlTemplate
        ///		xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///		TargetType=&quot;TabControl&quot;
        ///		&gt;
        ///	&lt;Grid&gt;
        ///		&lt;Grid.ColumnDefinitions&gt;
        ///			&lt;ColumnDefinition Width=&quot;Auto&quot; /&gt;
        ///			&lt;ColumnDefinition /&gt;
        ///		&lt;/Grid.ColumnDefinitions&gt;
        ///		&lt;ScrollViewer HorizontalScrollBarVisibility=&quot;Hidden&quot; VerticalScrollBarVisibility=&quot;Auto&quot; FlowDirection=&quot;RightToLeft&quot;&gt;
        ///			&lt;TabPanel x:Name=&quot;HeaderPanel&quot; Panel.ZIndex=&quot;0&quot; KeyboardNavigation.TabIndex=&quot;1&quot; IsI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TabControlLeftTemplate {
            get {
                return ResourceManager.GetString("TabControlLeftTemplate", resourceCulture);
            }
        }
    }
}
